### ISSUE TITLE
Load the combined CSV to memory and perform a simple EDA

### ISSUE THREAD

**Issue by cmmclaug** [UBC-MDS/dsci_525_group_6#7]
5. Load the combined CSV to memory and perform a simple EDA
rubric={correctness:10,reasoning:10}

- [x] Investigate at least two of the following approaches to reduce memory usage while performing the EDA (e.g., value_counts).
* Changing dtype of your data
* Load just columns what we want
* Loading in chunks
* Dask
- [x] Discuss your observations.

**Comment by KangboLu** [comment]
Reference to the lecture: https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/Lectures/Lecture_1_2.ipynb
